### PR TITLE
Add satelite crash

### PR DESCRIPTION
**Pull request by ravmustang**
satelite model and textures
cfgVehicles entry
stringtable had extra </Key> lines on recent additions. Cleaned up
added stringtable entry for satelite

### CODE REVIEW

**Comment by vbawol** [comment]
Looks good, except one thing the word Satelite should be Satellite

**Comment by ravmustang** [comment]
Lol I won't name any names on whom made the model! 
I was a follower!!!! Can't blame me lmao.
I see there is a conflict. You want me to edit this branch?

**Comment by vbawol** [comment]
Sure ya, either that or just make a new one, Don't worry about the "1 errored check" that is from Jenkins.

**Comment by Helion4** [comment]
I named it that to avoid any confusion between this and the real thing  :stuck_out_tongue_closed_eyes:

**Comment by ravmustang** [comment]
Spelling corrections made. 👍

**Pull request merged**
